[package]
name = "dank-paste"
version = "0.1.0"
authors = ["Wilson Birney <wpb@360scada.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
rand = "*"
multipart = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", "json"]
