[package]
name = "dank-paste"
version = "0.2.4"
authors = ["Wilson Birney <wpb@360scada.com>"]

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
rand = "*"
multipart = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
dank_codegen = { path = "./codegen" }

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["handlebars_templates", "json"]

[patch.crates-io]
ring = { git = "https://github.com/SergioBenitez/ring", branch = "v0.12" }
